#  █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
# ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
# ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
# ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝

[general]
import = [
  "~/.config/alacritty/themes/themes/catppuccin-mocha.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
# decorations = "None"
opacity = 1
blur = true
startup_mode = "Maximized"

# [window.padding]
# x = 5
# y = 5

[font]
size = 12

[font.normal]
family = "Monospace"

# [font.normal]
# family = "JetBrainsMono Nerd Font"
# style = "Regular"
#
# [font.bold]
# family = "JetBrainsMono Nerd Font"
# style = "Bold"
#
# [font.italic]
# family = "JetBrainsMono Nerd Font"
# style = "Italic"

[scrolling]
history = 10000   # Number of lines to remember in the scrollback buffer
multiplier = 3    # Scroll multiplier (lines per scroll event)
# smooth = true     # Enable smooth scrolling

[cursor.style]
shape = "Block"
blinking = "Always"

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/zsh"
